### ISSUE TITLE
Remove Main action from Strange Copy

### ISSUE THREAD

**Issue by danj3000** [onecrayon/api.ashes.live#20] opened 2020-12-01 13:37 UTC

**Comment by onecrayon** [comment] 2020-12-01 15:56
Duplicate of #19.

**Closed by onecrayon** 2020-12-01 15:56 UTC

**Comment by danj3000** [comment] 2020-12-01 21:17
well, sure, it's a dupe if you do strange copy at the same time as sympathy pain :-D

**Comment by onecrayon** [comment] 2020-12-01 23:17
Those aren't the same card?! 😱
